### ISSUE TITLE
xcode8出了点问题，不关闭了

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [reactnativecn/react-native-launch-image#3]
我在xcode8的debug模式下没问题，但是一旦切换成release版本就无法触发hide了~~~救命

**Comment by tdzl2003** [comment]
您好，请问您的RN版本多少？hide是否在异步方法中调用的？通常这种情况是因为前面脚本出现了报错，导致hide没有被执行到。你可以先暂时移除原生端显示launch-image的代码，再观察一下脚本部分功能是否执行正常，譬如在hide()之后调用alert看看是否执行到了之类。

**Comment by liuhuapiaoyuan** [comment]
就是非常奇怪，我的这个hide是放在setTimeout里面执行的。非常奇怪，第一次打开没问题，第二次打开就有不对了，最奇怪的是。另外我这个hide是放到ComponetDitMount里面的，我在前后alert，竟然连alert都没有执行

**Comment by liuhuapiaoyuan** [comment]
我现在的情况就是第一次安装app都正常，第二次打开app的时候，不触发ComponetDitMount 结果导致不触发hide方法，然后屏幕就一直卡着

**Comment by sunnylqm** [comment]
你确定你没有打错的话，我得说，**c**omponentDidMount的首字母是小写  @liuhuapiaoyuan

**Comment by liuhuapiaoyuan** [comment]
额 这是我随便打的。。。代码里面当然不会错了。。

**Comment by liuhuapiaoyuan** [comment]
我现在在初始化的页面cdm里面也写了hide，现在就可以隐藏了

**Comment by liuhuapiaoyuan** [comment]
我觉得我可能是用了redux-persist导致最外层的组件不触发cdm了
